# This file is a DRAFT schema based on prd_mvp.md (KISS version)
# Auto-generated by migrations, do not edit manually
# Use this as reference for creating migrations

ActiveRecord::Schema[8.0].define(version: 2025_12_16_000006) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  # ============================================================
  # Users (소비자 + 관리자)
  # ============================================================
  create_table "users", force: :cascade do |t|
    t.string "name", null: false
    t.string "phone", null: false
    t.string "email"
    t.string "address"

    # OAuth
    t.string "oauth_provider"  # kakao, naver, null (이메일 가입)
    t.string "oauth_uid"

    # Devise (이메일 가입용)
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"

    # Role
    t.string "role", default: "user", null: false  # user, admin

    # MFA (관리자 전용)
    t.datetime "last_2fa_at"  # 주 1회 재인증 체크
    t.string "otp_secret"     # SMS OTP 시크릿

    t.timestamps

    t.index ["phone"], unique: true
    t.index ["email"], unique: true, where: "email IS NOT NULL"
    t.index ["oauth_provider", "oauth_uid"], unique: true, where: "oauth_provider IS NOT NULL"
    t.index ["reset_password_token"], unique: true
  end

  # ============================================================
  # Farmers (농가)
  # ============================================================
  create_table "farmers", force: :cascade do |t|
    t.string "business_name", null: false      # 사업자명
    t.string "owner_name", null: false         # 대표자명
    t.string "phone", null: false

    # 암호화된 계좌 정보 (attr_encrypted)
    t.string "encrypted_account_info"
    t.string "encrypted_account_info_iv"

    # 승인 모드
    t.string "approval_mode", default: "manual", null: false  # manual(타입A), auto(타입B)

    # 재고 (타입 B 자동승인용, 타입 A도 사용 가능)
    t.integer "stock_quantity", default: 0, null: false

    # 알림 채널
    t.string "notification_method", default: "kakao", null: false  # kakao, sms

    # 인증 (타입 A용, 비밀번호는 보류 - 토큰만 사용)
    # t.string "pin_digest"  # 보류 (KISS)

    t.timestamps

    t.index ["phone"], unique: true
  end

  # ============================================================
  # Products (상품)
  # ============================================================
  create_table "products", force: :cascade do |t|
    t.bigint "farmer_id", null: false

    t.string "name", null: false
    t.text "description"
    t.decimal "price", precision: 10, scale: 2, null: false
    t.string "category"  # 예: 채소, 과일, 축산

    # 재고
    t.integer "stock_quantity", default: 0, null: false
    t.boolean "is_available", default: true, null: false  # 판매 가능 여부 토글

    # 이미지 (Active Storage)
    # has_one_attached :image

    t.timestamps

    t.index ["farmer_id"]
    t.index ["category"]
    t.index ["is_available"]
  end

  # ============================================================
  # Orders (주문)
  # ============================================================
  create_table "orders", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.bigint "farmer_id", null: false

    # 주문 정보
    t.string "order_number", null: false  # 예: ORD-20250116-001
    t.decimal "total_amount", precision: 10, scale: 2, null: false

    # 상태
    t.string "status", default: "pending", null: false
    # pending → farmer_review → confirmed → payment_pending → completed
    # rejected, cancelled

    # 상태 로그 (JSONB)
    t.jsonb "status_history", default: []
    # [{status: 'confirmed', at: '2025-01-16T10:00:00Z', by_id: 123, by_type: 'Farmer', note: '승인'}, ...]

    # 상태 로그 캐시 (쿼리/레포트용)
    t.datetime "last_status_changed_at"
    t.bigint "last_status_changed_by_id"
    t.string "last_status_changed_by_type"  # User, Farmer, Admin

    # 타임아웃
    t.datetime "timeout_at"  # farmer_review 상태에서 24시간

    # 상태별 타임스탬프
    t.datetime "confirmed_at"      # 농가 승인 시각
    t.datetime "completed_at"      # 입금 확인 완료 시각
    t.datetime "cancelled_at"      # 취소 시각
    t.datetime "rejected_at"       # 거절 시각

    # 거절 사유
    t.text "rejection_reason"

    t.timestamps

    t.index ["user_id"]
    t.index ["farmer_id"]
    t.index ["order_number"], unique: true
    t.index ["status"]
    t.index ["timeout_at"]
    t.index ["created_at"]
  end

  # ============================================================
  # OrderItems (주문 항목)
  # ============================================================
  create_table "order_items", force: :cascade do |t|
    t.bigint "order_id", null: false
    t.bigint "product_id", null: false

    t.integer "quantity", null: false
    t.decimal "price", precision: 10, scale: 2, null: false  # 주문 당시 가격

    t.timestamps

    t.index ["order_id"]
    t.index ["product_id"]
  end

  # ============================================================
  # Payments (입금 관리 - 간소화)
  # ============================================================
  create_table "payments", force: :cascade do |t|
    t.bigint "order_id", null: false

    t.decimal "amount", precision: 10, scale: 2, null: false
    t.string "status", default: "pending", null: false  # pending, verified

    # 관리자 확인 메모
    t.text "admin_note"  # 예: "1/15 전화 확인 완료 - 김OO 관리자"

    t.datetime "verified_at"  # 관리자 확인 시각

    t.timestamps

    t.index ["order_id"], unique: true
    t.index ["status"]
  end

  # ============================================================
  # Notifications (알림 - 토큰 관리 포함)
  # ============================================================
  create_table "notifications", force: :cascade do |t|
    t.bigint "order_id"
    t.bigint "farmer_id"

    # 알림 타입
    t.string "notification_type", null: false  # order_created, order_approved, order_rejected 등

    # 채널
    t.string "channel", null: false  # kakao, sms

    # 외부 메시지 ID (카카오/SMS 발송 결과)
    t.string "channel_msg_id"

    # 토큰 관리 (농가 알림톡 링크용)
    t.string "token_jti"       # JWT ID (30분 만료)
    t.datetime "expires_at"     # 만료 시각
    t.datetime "used_at"        # 사용 시각 (재사용 차단)

    # 발송 상태
    t.datetime "sent_at"
    t.string "status", default: "pending", null: false  # pending, sent, failed, delivered
    t.integer "retry_count", default: 0

    t.timestamps

    t.index ["order_id"]
    t.index ["farmer_id"]
    t.index ["token_jti"], unique: true, where: "token_jti IS NOT NULL"
    t.index ["status"]
    t.index ["created_at"]
  end

  # ============================================================
  # Foreign Keys
  # ============================================================
  add_foreign_key "products", "farmers"
  add_foreign_key "orders", "users"
  add_foreign_key "orders", "farmers"
  add_foreign_key "order_items", "orders"
  add_foreign_key "order_items", "products"
  add_foreign_key "payments", "orders"
  add_foreign_key "notifications", "orders"
  add_foreign_key "notifications", "farmers"
end

# ============================================================
# 제거된 테이블 (KISS)
# ============================================================
# - FarmerPolicies: 전역 타임아웃만 사용
# - PaymentEvents: Payments.admin_note로 대체
# - AccessTokens: Notifications에 token_jti/used_at/expires_at로 통합
# - AuditEvents: Orders.status_history (JSONB)로 대체

# ============================================================
# Active Storage (상품 이미지)
# ============================================================
# rails active_storage:install 실행 시 자동 생성:
# - active_storage_blobs
# - active_storage_attachments
# - active_storage_variant_records
